image_dimensions:
  height: 256
  width: 256

params:
  learning_rate: 0.001
  num_epochs: 20
  batch_size: 64

paths:
  data_mat: data/cars196/car_devkit/devkit/cars_train_annos.mat
  train_original: data/cars196/cars_train/cars_train
  test_original: data/cars196/cars_test/cars_test
  
explorations:
  classes_to_augment:
  - 2
  - 7
  - 10
  - 11
  - 12
  - 23
  - 25
  - 26
  - 27
  - 37
  - 39
  - 40
  - 41
  - 42
  - 45
  - 47
  - 49
  - 54
  - 55
  - 57
  - 60
  - 62
  - 64
  - 67
  - 68
  - 69
  - 71
  - 78
  - 88
  - 91
  - 92
  - 93
  - 99
  - 100
  - 102
  - 103
  - 116
  - 122
  - 124
  - 128
  - 129
  - 134
  - 136
  - 138
  - 141
  - 142
  - 143
  - 150
  - 152
  - 156
  - 157
  - 158
  - 159
  - 163
  - 169
  - 175
  - 176
  - 181
  - 185
  - 186
  - 196
  mean:
  - - 0.46911017016871714
    - 0.4588044100885678
    - 0.45401660039068426
  std:
  - - 0.2595635795076975
    - 0.2581902811790881
    - 0.26307361857439066
