image_dimensions:
  height: 256
  width: 256

params:
  learning_rate: 0.001
  num_epochs: 20
  batch_size: 64
  num_workers: 6

paths:
  data_mat: data/cars196/car_devkit/devkit/cars_train_annos.mat
  train_original: data/cars196/cars_train/cars_train
  test_original: data/cars196/cars_test/cars_test
  images: ./data/images
  
explorations:
  mean:
  - 0.46911017016871714
  - 0.4588044100885678
  - 0.45401660039068426
  std:
  - 0.2595635795076975
  - 0.2581902811790881
  - 0.26307361857439066
